// Code generated by procyon-cli. DO NOT EDIT.

package main

import coreplugins "github.com/bartek5186/procyon-core/plugins"

func installedPluginFactories() []coreplugins.Registration {
	return nil
}
